/**
 * Compression wrapper for Codex adapter
 * Provides optional compression for Codex JSONL output
 */

import { compressToolResult, estimateTokenSavings, type CompressionOptions } from "./compression.js";

export interface CodexCompressionConfig {
  /** Enable compression of tool results */
  compressToolResults?: boolean;
  /** Use RTK (reduced token keys) for JSON */
  useRTK?: boolean;
  /** Use Caveman compression for text (not recommended for code) */
  useCaveman?: boolean;
  /** Maximum context messages to keep */
  maxContextMessages?: number;
}

/**
 * Apply compression to Codex JSONL output if enabled
 * This is a conservative implementation that only compresses tool results
 * and NEVER touches code generated by the model
 */
export function maybeCompressCodexOutput(
  jsonlOutput: string,
  config: CodexCompressionConfig,
  onLog?: (channel: string, message: string) => Promise<void>
): string {
  // If compression is disabled, return original
  if (!config.compressToolResults) {
    return jsonlOutput;
  }

  try {
    const lines = jsonlOutput.split("\n");
    const compressed: string[] = [];
    let totalSavings = 0;
    let compressedCount = 0;

    for (const line of lines) {
      if (!line.trim()) {
        compressed.push(line);
        continue;
      }

      try {
        const entry = JSON.parse(line);

        // Only compress tool_result entries, NEVER code or commands
        if (entry.type === "tool_result" && entry.content && entry.content.length > 100) {
          const original = entry.content;
          
          // Try to parse as JSON for structured compression
          let compressedContent: string;
          try {
            const parsed = JSON.parse(original);
            compressedContent = compressToolResult(parsed, {
              useTOON: true,
              useRTK: config.useRTK ?? false,
              useCaveman: false, // Never use Caveman for tool results (may contain code)
              useVarman: true,
            });
          } catch {
            // Not JSON, apply text compression (but NOT Caveman - too aggressive for code)
            compressedContent = compressToolResult(original, {
              useTOON: false,
              useRTK: false,
              useCaveman: false,
              useVarman: true, // Only Varman for text (safer)
            });
          }

          // Only use compressed version if it's actually shorter
          if (compressedContent.length < original.length * 0.9) {
            entry.content = compressedContent;
            const savings = estimateTokenSavings(original, compressedContent);
            totalSavings += savings;
            compressedCount++;
          }
        }

        compressed.push(JSON.stringify(entry));
      } catch {
        // Not valid JSON, keep original line
        compressed.push(line);
      }
    }

    // Log compression stats if any compression happened
    if (compressedCount > 0 && onLog) {
      const avgSavings = Math.round(totalSavings / compressedCount);
      onLog(
        "stdout",
        `[paperclip] Compressed ${compressedCount} tool results (~${avgSavings}% avg token reduction)\n`
      ).catch(() => {});
    }

    return compressed.join("\n");
  } catch (err) {
    // If anything goes wrong, return original
    console.error("[compression] Error compressing Codex output:", err);
    return jsonlOutput;
  }
}

/**
 * Get compression options from Codex config
 */
export function getCodexCompressionConfig(config: Record<string, unknown>): CodexCompressionConfig {
  return {
    compressToolResults: config.compressToolResults === true,
    useRTK: config.useRTK === true,
    useCaveman: false, // Always false for Codex (code safety)
    maxContextMessages: typeof config.maxContextMessages === "number" ? config.maxContextMessages : undefined,
  };
}
